### ISSUE TITLE
mvrnorm uses corMat instead of covMat?

### ISSUE THREAD

**Issue by LukasWallrich** [schoam4/mc_power_med#10]
Unless I misread the code of `two_parrallel_mediators.R` and `two_serial_mediators.R`, the call to `mvrnorm()` uses `Sigma = corMat`, where I would expect it to refer to `covMat` (`corMat` is the default argument to `covMatp` in `powRep()` and does not appear to be specified otherwise when the function is called). The code in one_mediator.R is as I would expect it, with `covMatp = covMat` in the function definition.

Could you clarify if this difference is intentional or if it should be covMat in the two_mediator functions as well?

**Comment by schoam4** [comment]
Hi!
I'm just getting to this now (2021 has been a year!) That was definitely a bug, thanks for catching it!
