### ISSUE TITLE
(two_serial_mediators.R) typo

### ISSUE THREAD

**Issue by Joe-Wasserman** [schoam4/mc_power_med#7]
https://github.com/schoam4/mc_power_med/blob/master/code/two_serial_mediators.R#L95

Typo in input: "SDM2 <- as.numeric(input$SDM1)" should be "SDM2 <- as.numeric(input$SDM2)"

**Comment by schoam4** [comment]
Thanks you! The typo has been fixed .

**Comment by LukasWallrich** [comment]
Hi there - the same typo is present in two_parallel_mediators.R

SDM1 <- as.numeric(input$SDM1)
SDM2 <- as.numeric(input$**SDM1**)
