### ISSUE TITLE
(two_parallel_mediators.R) typo

### ISSUE THREAD

**Issue by LukasWallrich** [schoam4/mc_power_med#9]
Just realised that this should probably be a new issue, given that the previous one is closed. So here again.

SDM1 <- as.numeric(input$SDM1)
SDM2 <- as.numeric(input$**SDM1**)

Thanks for this very helpful tool! For my own purposes, I am currently expanding it to 3 parallel mediators - would you be interested in including that? Then I would submit a PR once I am done.

_Originally posted by @LukasWallrich in https://github.com/schoam4/mc_power_med/issues/7#issuecomment-753637020_

**Comment by LukasWallrich** [comment]
One more thing: this typo has also reappeared in the two_serial_mediators.R, possibly when you merged branches?

**Comment by schoam4** [comment]
Thanks for catching this! It should be fixed in the github versions.
